replicaCount: 1
image:
  repository: asia-northeast3-docker.pkg.dev/engaged-proxy-460415-d1/highfive-registry/data-collector
  tag: "f548dd4065dc935c6abcdc32ad92e073d8ad8218-15316758677"
  pullPolicy: IfNotPresent
fullnameOverride: "data-collector"
dependency:
  api_gateway:
    service_name: "api-gateway"
    port: 8080
  mongodb:
    service_name: "mongodb"
    port: 27017
  mysql:
    service_name: "mysql"
    port: 3306
service:
  port: 8086
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 200
  periodSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 200
  periodSeconds: 5
  failureThreshold: 3
config:
  SPRING_BATCH_JOB_ENABLED: "false"
