replicaCount: 1
image:
  repository: asia-northeast3-docker.pkg.dev/engaged-proxy-460415-d1/highfive-registry/api-gateway
  tag: "efb34ae615225f602c2ee28481a79053700abdf3-15409094778"
  pullPolicy: IfNotPresent
fullnameOverride: "api-gateway"
service:
  port: 8080
dependency:
  discovery:
    service_name: "discovery"
    port: 8761
resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "700m"
    memory: "1Gi"
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 3
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "highfive-cert"
    kubernetes.io/ingress.global-static-ip-name: "highfive-ip" # 정적 IP 할당
  hosts:
    - host: api.highfive.p-e.kr
      paths:
        - path: /
          pathType: Prefix
          port: 8080
